### ISSUE TITLE
information not needed

### ISSUE THREAD

**Issue by smartmarmot** [vagabondan/DBforBIX#3]
Please correct me if I'm wrong but I think there is no need to specify in the configuration file the DBList=
This because the list of database is already contaned in the configuration file and can be retrieved with Config.readConfigDB
called here:
it = pcfg.getKeys(GLOBAL_DB);
			while (it.hasNext()) {
				String key = it.next().toString();
				String[] keyparts = key.split("\\.");
				if (keyparts.length == 3)
					readConfigDB(keyparts[0], keyparts[1], keyparts[2], pcfg.getString(key));
			}
Maybe I'm not getting the real reason behind this, so let me know or I'll make it dynamic.

**Comment by vagabondan** [comment]
The reason to keep DBList comes from the following consideration:
we have 2 or more Zabbix Servers, which are serviced with the same DBforBix instance, each Zabbix Server could monitor its own set of DBs.
So it is rather some kind of security option: list of DBs for specific Zabbix Server. One can not get any data from DB which is not defined in appropriate DBList.

**Comment by smartmarmot** [comment]
Now i see the point, it make sense, thanks
